export function renderAdminPage() {
  return `<!doctype html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <meta name="theme-color" content="#111827" />
  <title>IVAI Admin</title>
  <script src="https://telegram.org/js/telegram-web-app.js"></script>
  <style>
    :root{--bg:#0b1020;--surface:#141b31;--surface2:#1d2745;--text:#f6f8ff;--muted:#aab5d6;--accent:#7c9cff;--ring:rgba(124,156,255,.45)}
    *{box-sizing:border-box}body{margin:0;background:linear-gradient(160deg,#0a0f1e,#121a33);color:var(--text);font:15px/1.6 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Tahoma,sans-serif;min-height:100dvh}
    button,input,textarea{font:inherit}button{min-height:44px;border:0;border-radius:12px;padding:10px 14px;color:#fff;background:var(--surface2);cursor:pointer}button:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid var(--ring);outline-offset:2px}.primary{background:linear-gradient(135deg,#667eea,#8a6bdf)}.ghost{background:transparent;border:1px solid #344167}
    main{width:min(100%,760px);margin:auto;padding:max(16px,env(safe-area-inset-top)) 16px max(28px,env(safe-area-inset-bottom))}.header{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:8px 0 22px}.brand{display:flex;gap:10px;align-items:center}.logo{width:42px;height:42px;border-radius:14px;display:grid;place-items:center;background:radial-gradient(circle at 30% 30%,#a9c1ff,#4350b5 55%,#202663);font-size:22px}.brand h1{font-size:18px;margin:0}.brand p{font-size:12px;color:var(--muted);margin:0}.status{font-size:12px;color:var(--muted)}
    .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.card{background:rgba(20,27,49,.92);border:1px solid #263251;border-radius:18px;padding:16px;box-shadow:0 12px 35px rgba(0,0,0,.16)}.metric b{font-size:24px;display:block}.metric span{color:var(--muted);font-size:12px}.section{margin-top:14px}.section h2{font-size:15px;margin:0 0 10px}.actions{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.hint{font-size:12px;color:var(--muted);margin:8px 0 0}.hidden{display:none}.notice{padding:12px;border-radius:12px;background:#2d2535;color:#ffd6dc;font-size:13px}.form{display:grid;gap:10px}.form label{font-size:13px;color:var(--muted)}textarea,input{width:100%;border:1px solid #344167;border-radius:12px;padding:11px;background:#0d1327;color:var(--text);resize:vertical}.row{display:flex;gap:10px;flex-wrap:wrap}.row button{flex:1}
    @media(max-width:420px){main{padding-inline:12px}.grid{grid-template-columns:1fr}.actions{grid-template-columns:1fr}.header{align-items:flex-start}.status{padding-top:8px}.metric b{font-size:22px}}
  </style>
</head>
<body><main>
  <header class="header"><div class="brand"><div class="logo">🪐</div><div><h1>IVAI Admin</h1><p id="subtitle">Secure, free-tier operations</p></div></div><span id="status" class="status">Checking access…</span></header>
  <div id="denied" class="notice hidden">This panel is available only to verified administrators.</div>
  <div id="dashboard" class="hidden">
    <section class="grid"><div class="card metric"><b id="users">—</b><span id="usersLabel">Active users</span></div><div class="card metric"><b id="queue">—</b><span id="queueLabel">Broadcast queue</span></div><div class="card metric"><b id="quota">—</b><span id="quotaLabel">AI budget remaining</span></div></section>
    <section class="card section"><h2 id="quickActions">Quick actions</h2><div class="actions"><button id="openBroadcast" class="primary">📣 New broadcast</button><button id="openGuard">🛡 Guard Mode</button><button id="openStats">📊 Reports</button><button id="openPolicies">⚙️ Usage policy</button></div></section>
    <section id="broadcast" class="card section hidden"><h2 id="broadcastTitle">Broadcast draft</h2><div class="form"><label id="contentLabel" for="content">Message</label><textarea id="content" rows="5" maxlength="3500" placeholder="Write your message…"></textarea><p id="broadcastHint" class="hint">Delivery is available only after preview and final confirmation. Paid broadcast is never used.</p><div class="row"><button id="preview" class="ghost">Preview</button><button id="create" class="primary">Create draft</button></div><div id="draftResult" class="hint"></div></div></section>
  </div>
</main>
<script>
  const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();const el=id=>document.getElementById(id);const dashboard=el('dashboard');const denied=el('denied');
  const copy={en:{subtitle:'Secure, free-tier operations',checking:'Checking access…',denied:'Access denied',deniedText:'This panel is available only to verified administrators.',verified:'Administrator verified',users:'Active users',queue:'Broadcast queue',quota:'AI budget remaining',quick:'Quick actions',newBroadcast:'📣 New broadcast',reports:'📊 Reports',policy:'⚙️ Usage policy',title:'Broadcast draft',message:'Message',placeholder:'Write your message…',hint:'Delivery is available only after preview and final confirmation. Paid broadcast is never used.',preview:'Preview',create:'Create draft',empty:'Write a message first.',previewPrefix:'Preview: ',created:'Draft created: ',failed:'Could not create the draft.'},fa:{subtitle:'عملیات امن با سهمیهٔ رایگان',checking:'در حال بررسی دسترسی…',denied:'دسترسی رد شد',deniedText:'این پنل فقط برای ادمین‌های تأییدشده قابل دسترسی است.',verified:'ادمین تأیید شد',users:'کاربران فعال',queue:'صف broadcast',quota:'بودجهٔ AI باقی‌مانده',quick:'عملیات سریع',newBroadcast:'📣 broadcast جدید',reports:'📊 گزارش‌ها',policy:'⚙️ سیاست مصرف',title:'پیش‌نویس broadcast',message:'متن پیام',placeholder:'پیام را بنویسید…',hint:'ارسال فقط پس از پیش‌نمایش و تأیید نهایی فعال می‌شود. ارسال پولی هرگز استفاده نمی‌شود.',preview:'پیش‌نمایش',create:'ساخت پیش‌نویس',empty:'ابتدا متن وارد کنید.',previewPrefix:'پیش‌نمایش: ',created:'پیش‌نویس ساخته شد: ',failed:'ساخت پیش‌نویس ناموفق بود.'}};
  const lang=tg?.initDataUnsafe?.user?.language_code==='fa'?'fa':'en',t=copy[lang];if(lang==='fa'){document.documentElement.lang='fa';document.documentElement.dir='rtl'}
  const labels={subtitle:'subtitle',status:'checking',denied:'deniedText',usersLabel:'users',queueLabel:'queue',quotaLabel:'quota',quickActions:'quick',openBroadcast:'newBroadcast',openStats:'reports',openPolicies:'policy',broadcastTitle:'title',contentLabel:'message',broadcastHint:'hint',preview:'preview',create:'create'};Object.entries(labels).forEach(([id,key])=>{if(el(id))el(id).textContent=t[key]});el('content').placeholder=t.placeholder;
  async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':tg?.initData||''},body:JSON.stringify(body||{})});return{ok:r.ok,data:await r.json().catch(()=>({}))}}
  async function boot(){try{const {ok,data}=await api('/admin/session');if(!ok||!data.admin){el('status').textContent=t.denied;denied.textContent=t.deniedText;denied.classList.remove('hidden');return}el('status').textContent=t.verified;dashboard.classList.remove('hidden');el('users').textContent=data.metrics?.activeUsers??'—';el('queue').textContent=data.metrics?.pendingBroadcasts??'—';el('quota').textContent=data.metrics?.aiBudgetRemaining??'—'}catch{el('status').textContent='Connection temporarily unavailable'}}
  el('openBroadcast').onclick=()=>el('broadcast').classList.toggle('hidden');el('preview').onclick=()=>{const value=el('content').value.trim();el('draftResult').textContent=value?(t.previewPrefix+value):t.empty};el('create').onclick=async()=>{const content=el('content').value.trim();if(!content)return;const {ok,data}=await api('/admin/broadcast/draft',{content});el('draftResult').textContent=ok?(t.created+data.id):t.failed};boot();
</script></body></html>`;
}
