export function renderAppPage(nonce = "") {
  return `<!doctype html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <meta name="theme-color" content="#07192f" />
  <meta name="color-scheme" content="dark" />
  <title>IVAI Terminal</title>
  <script nonce="${nonce}" src="https://telegram.org/js/telegram-web-app.js?63"></script>
  <style nonce="${nonce}">
    :root{--night:#040d1a;--navy:#07192f;--navy-2:#0a2340;--blue:#2c87ff;--blue-soft:#7dc6ff;--jade:#16b89b;--jade-soft:#6be0c5;--ink:#ecf8ff;--muted:#88a4bb;--line:rgba(125,198,255,.18);--danger:#ff7084;--panel:rgba(7,25,47,.86);--shadow:0 18px 55px rgba(0,4,13,.38);font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono",monospace}
    *{box-sizing:border-box}html,body{min-height:100%;background:var(--night)}body{margin:0;color:var(--ink);min-height:100dvh;background:radial-gradient(80% 58% at 50% -15%,rgba(44,135,255,.22),transparent 67%),radial-gradient(56% 45% at 100% 100%,rgba(22,184,155,.13),transparent 72%),var(--night)}button,textarea{font:inherit}button{cursor:pointer}button:focus-visible,textarea:focus-visible{outline:2px solid var(--jade-soft);outline-offset:3px}
    main{width:min(100%,800px);min-height:100dvh;margin:auto;padding:max(14px,env(safe-area-inset-top)) 14px max(14px,env(safe-area-inset-bottom));display:flex;flex-direction:column;gap:12px}.terminal{display:flex;flex:1;min-height:0;flex-direction:column;border:1px solid var(--line);border-radius:20px;background:linear-gradient(145deg,rgba(10,35,64,.96),rgba(4,13,26,.98));box-shadow:var(--shadow);overflow:hidden}
    .topbar{display:flex;align-items:center;gap:10px;min-height:54px;padding:12px 15px;border-bottom:1px solid var(--line);background:linear-gradient(90deg,rgba(44,135,255,.10),rgba(22,184,155,.08))}.glyph{width:29px;height:29px;display:grid;place-items:center;border:1px solid rgba(107,224,197,.52);border-radius:9px;color:var(--jade-soft);font-size:15px;box-shadow:inset 0 0 16px rgba(22,184,155,.11)}.identity{min-width:0;flex:1}.identity b{display:block;color:var(--blue-soft);font-size:13px;letter-spacing:.13em}.identity span{display:block;margin-top:2px;color:var(--muted);font-size:10px;letter-spacing:.04em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.signal{display:flex;align-items:center;gap:6px;color:var(--jade-soft);font-size:10px;letter-spacing:.08em;white-space:nowrap}.signal i{width:7px;height:7px;border-radius:999px;background:var(--jade);box-shadow:0 0 12px var(--jade)}.signal.off{color:var(--muted)}.signal.off i{background:var(--muted);box-shadow:none}
    .meta{display:flex;gap:7px;flex-wrap:wrap;padding:10px 15px;border-bottom:1px solid rgba(125,198,255,.11);background:rgba(4,13,26,.42)}.chip{max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;border:1px solid rgba(44,135,255,.24);border-radius:999px;padding:4px 8px;color:var(--blue-soft);background:rgba(44,135,255,.08);font-size:10px}.chip.jade{color:var(--jade-soft);border-color:rgba(22,184,155,.30);background:rgba(22,184,155,.08)}
    #feed{flex:1;min-height:240px;overflow:auto;overscroll-behavior:contain;padding:17px 15px 8px;scrollbar-color:rgba(125,198,255,.35) transparent}.entry{display:grid;grid-template-columns:74px minmax(0,1fr);gap:10px;padding:0 0 16px;animation:arrive .16s ease-out}.entry .tag{padding-top:1px;color:var(--muted);font-size:10px;letter-spacing:.07em;text-align:right}.entry.user .tag{color:var(--blue-soft)}.entry.assistant .tag{color:var(--jade-soft)}.entry.error .tag{color:var(--danger)}.entry .body{min-width:0;white-space:pre-wrap;overflow-wrap:anywhere;font-family:inherit;font-size:13px;line-height:1.68}.entry.system .body{color:var(--muted)}.entry.pending .body{color:var(--jade-soft)}.entry.pending .body::after{content:"";display:inline-block;width:7px;height:13px;margin-inline-start:4px;vertical-align:-2px;background:var(--jade);animation:blink 850ms step-end infinite}@keyframes blink{50%{opacity:0}}@keyframes arrive{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:translateY(0)}}
    .composer{padding:12px;border-top:1px solid var(--line);background:rgba(4,13,26,.72)}.inputShell{display:flex;align-items:flex-end;gap:9px;border:1px solid rgba(44,135,255,.34);border-radius:14px;padding:8px 8px 8px 12px;background:rgba(2,10,20,.72);box-shadow:inset 0 1px 0 rgba(125,198,255,.08)}.prompt{color:var(--jade-soft);padding:8px 0;font-weight:700;font-size:16px;line-height:1}textarea{min-width:0;flex:1;max-height:130px;border:0;outline:0;resize:none;background:transparent;color:var(--ink);font-size:14px;line-height:1.45;padding:5px 0}textarea::placeholder{color:#5f7c96}.send{width:38px;height:38px;border:1px solid rgba(107,224,197,.45);border-radius:10px;background:linear-gradient(145deg,#118f7b,#0a665d);color:#e8fffa;font-size:16px;font-weight:800;box-shadow:0 6px 16px rgba(0,0,0,.22);transition:transform .15s ease,filter .15s ease}.send:active{transform:scale(.95)}.send:hover{filter:brightness(1.12)}.send:disabled{cursor:not-allowed;opacity:.42;filter:none}.hint{display:flex;justify-content:space-between;gap:10px;margin:8px 3px 0;color:var(--muted);font-size:10px;line-height:1.4}.hint b{color:var(--jade-soft);font-weight:600}.hidden{display:none!important}
    @media(max-width:460px){main{padding-inline:9px}.terminal{border-radius:16px}.topbar{padding-inline:12px}.identity b{font-size:12px}.signal{font-size:9px}.meta{padding-inline:12px}#feed{padding-inline:12px}.entry{grid-template-columns:61px minmax(0,1fr);gap:8px}.entry .body{font-size:12.5px}.hint span:last-child{display:none}}
    @media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important}}
  </style>
</head>
<body>
  <main>
    <section class="terminal" aria-label="IVAI Terminal">
      <header class="topbar">
        <div class="glyph" aria-hidden="true">◆</div>
        <div class="identity"><b>IVAI // TERMINAL</b><span id="subtitle">A free, private Telegram workspace</span></div>
        <div id="signal" class="signal off"><i></i><span>CONNECTING</span></div>
      </header>
      <div class="meta" aria-label="Terminal settings"><span id="modeChip" class="chip">MODE: —</span><span id="modelChip" class="chip">MODEL: AUTO</span><span id="memoryChip" class="chip jade">MEMORY: OFF</span></div>
      <div id="feed" aria-live="polite" aria-label="Conversation transcript"></div>
      <form id="composer" class="composer">
        <div class="inputShell"><span class="prompt" aria-hidden="true">›_</span><textarea id="input" rows="1" maxlength="12000" placeholder="Ask IVAI anything…" aria-label="Message IVAI"></textarea><button id="send" class="send" type="submit" aria-label="Send message">↵</button></div>
        <div class="hint"><span><b>ENTER</b> send · <b>SHIFT+ENTER</b> newline</span><span id="quota">FREE ROUTE</span></div>
      </form>
    </section>
  </main>
  <script nonce="${nonce}">
    (function(){
      var tg=window.Telegram&&window.Telegram.WebApp;var feed=document.getElementById('feed');var form=document.getElementById('composer');var input=document.getElementById('input');var send=document.getElementById('send');var signal=document.getElementById('signal');var modeChip=document.getElementById('modeChip');var modelChip=document.getElementById('modelChip');var memoryChip=document.getElementById('memoryChip');var quota=document.getElementById('quota');var pending=null;var busy=false;
      var copy={en:{hello:'Terminal ready. One message uses one free AI route.',placeholder:'Ask IVAI anything…',you:'YOU',ivai:'IVAI',system:'SYSTEM',thinking:'Thinking through one free route',offline:'Open IVAI Terminal from Telegram.',temporary:'The terminal cannot connect right now.'},fa:{hello:'ترمینال آماده است. هر پیام فقط از یک مسیر رایگان AI استفاده می‌کند.',placeholder:'هر چیزی از IVAI بپرسید…',you:'شما',ivai:'IVAI',system:'سیستم',thinking:'در حال پردازش با یک مسیر رایگان',offline:'ترمینال IVAI را از داخل Telegram باز کنید.',temporary:'اتصال ترمینال فعلاً ممکن نیست.'},ar:{hello:'المحطة جاهزة. كل رسالة تستخدم مسار ذكاء اصطناعي مجانيًا واحدًا.',placeholder:'اسأل IVAI أي شيء…',you:'أنت',ivai:'IVAI',system:'النظام',thinking:'جارٍ التفكير عبر مسار مجاني واحد',offline:'افتح IVAI Terminal من داخل Telegram.',temporary:'يتعذر اتصال المحطة الآن.'}};
      var t=copy.en;function setSignal(on,label){signal.className='signal'+(on?'':' off');signal.querySelector('span').textContent=label||(on?'FREE ROUTE':'OFFLINE')}
      function append(kind,label,text){var row=document.createElement('article');row.className='entry '+kind;var tag=document.createElement('div');tag.className='tag';tag.textContent=label;var body=document.createElement('div');body.className='body';body.textContent=text;row.append(tag,body);feed.appendChild(row);feed.scrollTop=feed.scrollHeight;return row}
      function autoSize(){input.style.height='auto';input.style.height=Math.min(input.scrollHeight,130)+'px'}function setBusy(value){busy=value;send.disabled=value;input.disabled=value}
      function api(path,body){return fetch(path,{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':tg&&tg.initData||''},body:body?JSON.stringify(body):'{}'}).then(function(r){return r.json().catch(function(){return {ok:false,code:'BAD_RESPONSE'}}).then(function(data){return {status:r.status,data:data}})})}
      function localized(settings){var language=settings.language||'en';t=copy[language]||copy.en;document.documentElement.lang=language;document.documentElement.dir=(language==='fa'||language==='ar')?'rtl':'ltr';input.placeholder=t.placeholder;document.getElementById('subtitle').textContent=language==='fa'?'فضای کاری خصوصی و رایگان Telegram':language==='ar'?'مساحة عمل Telegram خاصة ومجانية':'A free, private Telegram workspace';modeChip.textContent='MODE: '+String(settings.mode||'auto').toUpperCase();modelChip.textContent='MODEL: '+(settings.selectedModel?'SELECTED':'AUTO');memoryChip.textContent='MEMORY: '+(settings.memoryEnabled?'ON':'OFF');}
      async function boot(){if(!tg){append('error',t.system,t.offline);setSignal(false,'TELEGRAM ONLY');setBusy(true);return}try{tg.ready();tg.expand();try{tg.setHeaderColor&&tg.setHeaderColor('#07192f');tg.setBottomBarColor&&tg.setBottomBarColor('#07192f')}catch(ignore){}var result=await api('/app/session');if(!result.data.ok){throw new Error(result.data.code||'UNAUTHORIZED')}localized(result.data.settings||{});append('system',t.system,t.hello);setSignal(true,'FREE ROUTE');input.focus()}catch(error){append('error',t.system,t.temporary);setSignal(false,'RECONNECT');setBusy(true)}}
      form.addEventListener('submit',async function(event){event.preventDefault();var text=input.value.trim();if(!text||busy)return;append('user',t.you,text);input.value='';autoSize();setBusy(true);pending=append('assistant pending',t.ivai,t.thinking);try{var result=await api('/app/chat',{text:text});if(pending){pending.remove();pending=null}if(result.data.ok){append('assistant',t.ivai,result.data.text);quota.textContent='FREE ROUTE · '+String(result.data.remaining)+' LEFT';modeChip.textContent='MODE: '+String(result.data.mode||'auto').toUpperCase();modelChip.textContent='MODEL: '+(result.data.model||'AUTO').replace(/^@cf\//,'').toUpperCase()}else{append('error',t.system,result.data.message||t.temporary)}}catch(error){if(pending){pending.remove();pending=null}append('error',t.system,t.temporary)}finally{setBusy(false);input.focus()}});
      input.addEventListener('input',autoSize);input.addEventListener('keydown',function(event){if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();form.requestSubmit()}});boot();
    })();
  </script>
</body>
</html>`;
}
