export function renderAppPage(nonce = "") {
  return `<!doctype html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <meta name="theme-color" content="#07192f" />
  <meta name="color-scheme" content="dark" />
  <title>IVAI Terminal</title>
  <script nonce="${nonce}" src="https://telegram.org/js/telegram-web-app.js?63"></script>
  <style nonce="${nonce}">
    :root{--night:#030a13;--navy:#07192f;--navy-2:#0d2b4d;--blue:#2c87ff;--blue-soft:#8dccff;--jade:#16b89b;--jade-soft:#79ead2;--ink:#f1f8ff;--muted:#8ca5bb;--muted-2:#5f7890;--line:rgba(141,204,255,.16);--panel:rgba(8,27,49,.8);--panel-2:rgba(13,43,77,.68);--danger:#ff7c8f;--warning:#ffcc70;--shadow:0 28px 70px rgba(0,3,10,.45);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
    *{box-sizing:border-box}html,body{min-height:100%;background:var(--night)}body{margin:0;min-height:100dvh;color:var(--ink);background:radial-gradient(900px 480px at 50% -170px,rgba(44,135,255,.3),transparent 68%),radial-gradient(700px 380px at 105% 105%,rgba(22,184,155,.16),transparent 70%),var(--night)}button,textarea{font:inherit}button{cursor:pointer}button:focus-visible,textarea:focus-visible{outline:2px solid var(--jade-soft);outline-offset:3px}
    main{width:min(100%,880px);min-height:100dvh;margin:auto;padding:max(16px,env(safe-area-inset-top)) 16px max(16px,env(safe-area-inset-bottom));display:flex;flex-direction:column}.workspace{position:relative;display:flex;min-height:0;flex:1;flex-direction:column;overflow:hidden;border:1px solid var(--line);border-radius:26px;background:linear-gradient(155deg,rgba(11,37,66,.96),rgba(3,10,19,.98) 55%);box-shadow:var(--shadow)}
    .topbar{display:flex;align-items:center;gap:12px;padding:15px 17px 14px;border-bottom:1px solid var(--line);background:linear-gradient(100deg,rgba(44,135,255,.13),rgba(22,184,155,.08) 72%,transparent)}.mark{width:34px;height:34px;display:grid;place-items:center;flex:0 0 auto;border:1px solid rgba(121,234,210,.6);border-radius:11px;background:linear-gradient(145deg,rgba(22,184,155,.22),rgba(44,135,255,.1));box-shadow:inset 0 0 20px rgba(121,234,210,.09);color:var(--jade-soft);font-size:17px}.brand{min-width:0;flex:1}.brand b{display:block;color:#dff5ff;font-size:13px;letter-spacing:.12em}.brand span{display:block;overflow:hidden;margin-top:2px;color:var(--muted);font-size:11px;white-space:nowrap;text-overflow:ellipsis}.status{display:flex;align-items:center;gap:7px;border:1px solid rgba(140,165,187,.2);border-radius:999px;padding:6px 9px;color:var(--muted);background:rgba(3,10,19,.34);font-size:10px;font-weight:700;letter-spacing:.08em;white-space:nowrap}.status i{width:7px;height:7px;border-radius:50%;background:var(--muted);box-shadow:none}.status.online{color:var(--jade-soft);border-color:rgba(22,184,155,.32)}.status.online i{background:var(--jade);box-shadow:0 0 12px rgba(22,184,155,.92)}.status.warning{color:var(--warning);border-color:rgba(255,204,112,.34)}.status.warning i{background:var(--warning);box-shadow:0 0 12px rgba(255,204,112,.65)}
    .context{display:flex;align-items:center;gap:8px;overflow:auto;padding:11px 17px;border-bottom:1px solid rgba(141,204,255,.1);background:rgba(3,10,19,.32);scrollbar-width:none}.context::-webkit-scrollbar{display:none}.chip{display:inline-flex;align-items:center;gap:5px;flex:0 0 auto;border:1px solid rgba(141,204,255,.22);border-radius:999px;padding:5px 9px;color:var(--blue-soft);background:rgba(44,135,255,.08);font-size:10px;font-weight:700;letter-spacing:.04em}.chip.jade{border-color:rgba(22,184,155,.27);color:var(--jade-soft);background:rgba(22,184,155,.08)}.chip svg{width:11px;height:11px}
    #feed{display:flex;flex:1;min-height:230px;flex-direction:column;gap:13px;overflow:auto;padding:22px 17px 12px;scrollbar-color:rgba(141,204,255,.32) transparent}.welcome{max-width:560px;margin:0 auto 5px;text-align:center}.eyebrow{display:inline-flex;align-items:center;gap:6px;border:1px solid rgba(22,184,155,.22);border-radius:999px;padding:5px 9px;color:var(--jade-soft);background:rgba(22,184,155,.08);font-size:10px;font-weight:750;letter-spacing:.1em}.welcome h1{margin:11px 0 7px;font-size:clamp(24px,5.8vw,34px);letter-spacing:-.045em;line-height:1.06}.welcome p{max-width:460px;margin:0 auto;color:var(--muted);font-size:13px;line-height:1.65}.suggestions{display:flex;flex-wrap:wrap;justify-content:center;gap:7px;margin-top:17px}.suggestion{border:1px solid rgba(141,204,255,.18);border-radius:11px;padding:8px 10px;color:#c4e4ff;background:rgba(44,135,255,.07);font-size:11px;transition:transform .15s ease,background .15s ease,border-color .15s ease}.suggestion:hover{border-color:rgba(121,234,210,.42);background:rgba(22,184,155,.11);transform:translateY(-1px)}
    .entry{display:flex;gap:9px;align-items:flex-start;max-width:92%;animation:arrive .18s ease-out}.entry.user{align-self:flex-end;flex-direction:row-reverse}.entry.system,.entry.error{align-self:center;max-width:100%}.avatar{display:grid;place-items:center;width:27px;height:27px;flex:0 0 auto;border:1px solid rgba(141,204,255,.22);border-radius:9px;background:rgba(44,135,255,.11);color:var(--blue-soft);font-size:10px;font-weight:800}.entry.assistant .avatar{border-color:rgba(22,184,155,.28);background:rgba(22,184,155,.1);color:var(--jade-soft)}.entry.user .avatar{background:rgba(44,135,255,.16);color:#cceaff}.bubble{min-width:0;border:1px solid rgba(141,204,255,.14);border-radius:15px;border-top-left-radius:5px;padding:10px 12px;color:#e8f5ff;background:rgba(10,34,60,.76);box-shadow:0 8px 20px rgba(0,0,0,.12);font-size:13px;line-height:1.62;white-space:pre-wrap;overflow-wrap:anywhere}.entry.user .bubble{border-color:rgba(44,135,255,.3);border-top-left-radius:15px;border-top-right-radius:5px;background:linear-gradient(140deg,rgba(34,114,220,.31),rgba(14,55,100,.8))}.entry.assistant .bubble{border-color:rgba(22,184,155,.18);background:linear-gradient(145deg,rgba(11,59,77,.75),rgba(7,29,50,.88))}.entry.system .bubble,.entry.error .bubble{max-width:520px;border-radius:12px;color:var(--muted);background:rgba(3,10,19,.5);font-size:11px;text-align:center}.entry.error .bubble{border-color:rgba(255,124,143,.25);color:#ffc2cc}.entry.pending .bubble{color:var(--jade-soft)}.entry.pending .bubble::after{display:inline-block;width:7px;height:14px;margin-inline-start:5px;background:var(--jade);content:"";vertical-align:-2px;animation:blink 900ms step-end infinite}@keyframes blink{50%{opacity:0}}@keyframes arrive{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:translateY(0)}}
    .retry{align-self:center;border:1px solid rgba(121,234,210,.36);border-radius:10px;padding:8px 11px;color:var(--jade-soft);background:rgba(22,184,155,.1);font-size:11px;font-weight:750}.retry:hover{background:rgba(22,184,155,.18)}.composer{padding:13px 14px 12px;border-top:1px solid var(--line);background:linear-gradient(180deg,rgba(3,10,19,.22),rgba(3,10,19,.82))}.composerShell{display:flex;align-items:flex-end;gap:10px;border:1px solid rgba(141,204,255,.32);border-radius:16px;padding:8px 8px 8px 13px;background:rgba(2,9,17,.72);box-shadow:inset 0 1px 0 rgba(255,255,255,.04),0 8px 24px rgba(0,0,0,.14)}.composerShell:focus-within{border-color:rgba(121,234,210,.62);box-shadow:0 0 0 3px rgba(22,184,155,.08),inset 0 1px 0 rgba(255,255,255,.04)}.prompt{padding:8px 0;color:var(--jade-soft);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:18px;font-weight:800;line-height:1}textarea{min-width:0;flex:1;max-height:130px;border:0;outline:0;resize:none;background:transparent;color:var(--ink);font-size:14px;line-height:1.45;padding:6px 0}textarea::placeholder{color:var(--muted-2)}.send{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-width:42px;height:40px;border:1px solid rgba(121,234,210,.55);border-radius:12px;padding:0 12px;background:linear-gradient(145deg,#129d87,#0b6d63);box-shadow:0 8px 18px rgba(0,0,0,.2);color:#edfffb;font-size:12px;font-weight:800;transition:transform .15s ease,filter .15s ease}.send svg{width:15px;height:15px}.send:hover{filter:brightness(1.1)}.send:active{transform:scale(.96)}.send:disabled{cursor:not-allowed;opacity:.4;filter:none}.footer{display:flex;justify-content:space-between;gap:8px;margin:8px 3px 0;color:var(--muted);font-size:10px;line-height:1.4}.footer b{color:var(--jade-soft);font-weight:750}.hidden{display:none!important}
    @media(max-width:520px){main{padding:0}.workspace{border-right:0;border-left:0;border-radius:0;min-height:100dvh}.topbar{padding-inline:14px}.context{padding-inline:14px}#feed{padding:20px 14px 10px}.entry{max-width:96%}.welcome h1{font-size:28px}.suggestions{gap:6px}.suggestion{font-size:10px}.composer{padding:11px 10px}.send{min-width:40px;padding:0 10px}.send span{display:none}.footer span:last-child{display:none}}
    @media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important}}
  </style>
</head>
<body>
  <main>
    <section class="workspace" aria-label="IVAI Terminal">
      <header class="topbar">
        <div class="mark" aria-hidden="true">◆</div>
        <div class="brand"><b>IVAI // TERMINAL</b><span id="subtitle">Private AI workspace inside Telegram</span></div>
        <div id="status" class="status"><i></i><span>CONNECTING</span></div>
      </header>
      <div class="context" aria-label="Current IVAI settings">
        <span id="modeChip" class="chip">MODE · —</span>
        <span id="modelChip" class="chip">MODEL · AUTO</span>
        <span id="memoryChip" class="chip jade">MEMORY · OFF</span>
        <span id="quotaChip" class="chip jade">FREE ROUTE</span>
      </div>
      <div id="feed" aria-live="polite" aria-label="Conversation"></div>
      <form id="composer" class="composer">
        <div class="composerShell"><span class="prompt" aria-hidden="true">›</span><textarea id="input" rows="1" maxlength="12000" placeholder="Ask IVAI anything…" aria-label="Message IVAI"></textarea><button id="send" class="send" type="submit" aria-label="Send message"><span>Send</span><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M21 3 10.4 13.6M21 3l-6.7 18-3.9-7.4L3 9.7 21 3Z" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg></button></div>
        <div class="footer"><span><b>ENTER</b> send · <b>SHIFT + ENTER</b> newline</span><span id="connectionHint">Secure Telegram session required</span></div>
      </form>
    </section>
  </main>
  <script nonce="${nonce}">
    (function(){
      var tg=window.Telegram&&window.Telegram.WebApp;var feed=document.getElementById('feed');var form=document.getElementById('composer');var input=document.getElementById('input');var send=document.getElementById('send');var status=document.getElementById('status');var modeChip=document.getElementById('modeChip');var modelChip=document.getElementById('modelChip');var memoryChip=document.getElementById('memoryChip');var quotaChip=document.getElementById('quotaChip');var connectionHint=document.getElementById('connectionHint');var busy=false;var pending=null;var initData='';var settings=null;var booted=false;
      var copy={en:{title:'Your private AI workspace',hello:'Start a conversation, explore an idea, or turn a rough thought into something clear.',placeholder:'Ask IVAI anything…',you:'You',ivai:'IVAI',system:'System',connecting:'Connecting securely…',ready:'Free route ready',expired:'Your Telegram session needs a refresh. Reopen IVAI Terminal from the bot.',missing:'Open IVAI Terminal from inside Telegram to start a secure session.',retry:'Reconnect',temporary:'The free route is temporarily busy. Try again in a moment.',suggestions:['Plan my next steps','Explain a concept','Polish my writing']},fa:{title:'فضای کار خصوصی AI شما',hello:'یک گفت‌وگو را شروع کنید، ایده‌ای را بررسی کنید یا متن خود را شفاف‌تر کنید.',placeholder:'هر چیزی از IVAI بپرسید…',you:'شما',ivai:'IVAI',system:'سیستم',connecting:'اتصال امن در حال انجام است…',ready:'مسیر رایگان آماده است',expired:'نشست Telegram نیاز به تازه‌سازی دارد. IVAI Terminal را دوباره از داخل بات باز کنید.',missing:'برای آغاز نشست امن، IVAI Terminal را از داخل Telegram باز کنید.',retry:'اتصال دوباره',temporary:'مسیر رایگان فعلاً مشغول است. کمی بعد دوباره امتحان کنید.',suggestions:['برایم برنامه بساز','یک مفهوم را توضیح بده','متنم را بهتر کن']},ar:{title:'مساحة الذكاء الاصطناعي الخاصة بك',hello:'ابدأ محادثة أو استكشف فكرة أو حسّن نصك.',placeholder:'اسأل IVAI أي شيء…',you:'أنت',ivai:'IVAI',system:'النظام',connecting:'جارٍ الاتصال بأمان…',ready:'المسار المجاني جاهز',expired:'تحتاج جلسة Telegram إلى تحديث. افتح IVAI Terminal مجددًا من البوت.',missing:'افتح IVAI Terminal من داخل Telegram لبدء جلسة آمنة.',retry:'إعادة الاتصال',temporary:'المسار المجاني مشغول مؤقتًا. حاول بعد قليل.',suggestions:['خطط لخطواتي التالية','اشرح مفهومًا','حسّن كتابتي']}};var t=copy.en;
      function setStatus(kind,label){status.className='status '+(kind||'');status.querySelector('span').textContent=label}function haptic(type){try{var api=tg&&tg.HapticFeedback;if(api&&api[type])api[type]('light')}catch(ignore){}}function scroll(){feed.scrollTop=feed.scrollHeight}function append(kind,label,text){var row=document.createElement('article');row.className='entry '+kind;var avatar=document.createElement('div');avatar.className='avatar';avatar.textContent=kind==='assistant'||kind==='pending'?'◆':kind==='user'?'›':'i';var bubble=document.createElement('div');bubble.className='bubble';bubble.textContent=text;row.append(avatar,bubble);feed.appendChild(row);scroll();return row}function setBusy(value){busy=value;send.disabled=value;input.disabled=value}function autoSize(){input.style.height='auto';input.style.height=Math.min(input.scrollHeight,130)+'px'}function clearWelcome(){var welcome=feed.querySelector('.welcome');if(welcome)welcome.remove()}function actionButton(label,handler){var button=document.createElement('button');button.type='button';button.className='retry';button.textContent=label;button.addEventListener('click',handler);feed.appendChild(button);scroll();return button}function retryButton(){var old=feed.querySelector('.retry');if(old)old.remove();actionButton(t.retry,function(){boot(true)})}
      function api(path,body){var controller=new AbortController();var timer=setTimeout(function(){controller.abort()},45000);return fetch(path,{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':initData},body:body?JSON.stringify(body):'{}',signal:controller.signal}).then(function(response){return response.json().catch(function(){return {ok:false,code:'BAD_RESPONSE'}}).then(function(data){return {status:response.status,data:data}})}).finally(function(){clearTimeout(timer)})}
      function localize(next){var language=next.language||'en';t=copy[language]||copy.en;document.documentElement.lang=language;document.documentElement.dir=(language==='fa'||language==='ar')?'rtl':'ltr';document.getElementById('subtitle').textContent=language==='fa'?'فضای کار خصوصی AI در Telegram':language==='ar'?'مساحة AI خاصة داخل Telegram':'Private AI workspace inside Telegram';input.placeholder=t.placeholder;modeChip.textContent='MODE · '+String(next.mode||'auto').toUpperCase();modelChip.textContent='MODEL · '+(next.selectedModel?'SELECTED':'AUTO');memoryChip.textContent='MEMORY · '+(next.memoryEnabled?'ON':'OFF')}
      function welcome(){var firstName=tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user&&tg.initDataUnsafe.user.first_name;var card=document.createElement('section');card.className='welcome';var eyebrow=document.createElement('div');eyebrow.className='eyebrow';eyebrow.textContent='◆ IVAI WORKSPACE';var title=document.createElement('h1');title.textContent=(firstName?firstName+', ':'')+t.title;var body=document.createElement('p');body.textContent=t.hello;var suggestions=document.createElement('div');suggestions.className='suggestions';t.suggestions.forEach(function(value){var button=document.createElement('button');button.type='button';button.className='suggestion';button.textContent=value;button.addEventListener('click',function(){input.value=value;autoSize();input.focus()});suggestions.appendChild(button)});card.append(eyebrow,title,body,suggestions);feed.appendChild(card);scroll()}
      function connectionError(result){var code=result&&result.data&&result.data.code;if(code==='CHANNEL_REQUIRED'){append('error',t.system,'Join @ILIVIR3 to unlock IVAI Terminal. After joining, return here and reconnect.');setStatus('warning','JOIN REQUIRED');connectionHint.textContent='Membership in @ILIVIR3 is required';actionButton('↗ Join @ILIVIR3',function(){try{if(tg&&tg.openTelegramLink){tg.openTelegramLink('https://t.me/ILIVIR3')}else{window.location.href='https://t.me/ILIVIR3'}}catch(ignore){window.location.href='https://t.me/ILIVIR3'}});actionButton(t.retry,function(){boot(true)});setBusy(true);return}var message=code==='UNAUTHORIZED'?(initData?t.expired:t.missing):t.temporary;append('error',t.system,message);setStatus('warning','RECONNECT');connectionHint.textContent=code==='UNAUTHORIZED'?'Refresh from Telegram':'Tap reconnect to try again';retryButton();setBusy(true)}
      async function boot(retry){if(busy&&!retry)return;feed.innerHTML='';setBusy(false);setStatus('',t.connecting);connectionHint.textContent='Validating Telegram session';initData=String(tg&&tg.initData||'');if(!tg||!initData){connectionError({data:{code:'UNAUTHORIZED'}});return}try{tg.ready();tg.expand();try{tg.setHeaderColor&&tg.setHeaderColor('#07192f');tg.setBackgroundColor&&tg.setBackgroundColor('#030a13');tg.setBottomBarColor&&tg.setBottomBarColor('#07192f')}catch(ignore){}var result=await api('/app/session');if(!result.data.ok)throw result;settings=result.data.settings||{};localize(settings);welcome();setStatus('online','SECURE');connectionHint.textContent=t.ready;booted=true;input.focus()}catch(error){connectionError(error&&error.data?error:null)}}
      form.addEventListener('submit',async function(event){event.preventDefault();var text=input.value.trim();if(!text||busy||!booted)return;clearWelcome();append('user',t.you,text);input.value='';autoSize();setBusy(true);pending=append('pending',t.ivai,'');pending.querySelector('.bubble').textContent=t.connecting;try{var result=await api('/app/chat',{text:text});if(pending){pending.remove();pending=null}if(result.data.ok){append('assistant',t.ivai,result.data.text);quotaChip.textContent='FREE ROUTE · '+String(result.data.remaining)+' LEFT';modeChip.textContent='MODE · '+String(result.data.mode||'auto').toUpperCase();modelChip.textContent='MODEL · '+String(result.data.model||'AUTO').replace(/^@cf\//,'').toUpperCase();setStatus('online','SECURE');connectionHint.textContent=t.ready;haptic('impactOccurred')}else{append('error',t.system,result.data.message||t.temporary);if(result.data.code==='UNAUTHORIZED'||result.data.code==='CHANNEL_REQUIRED'){booted=false;connectionError(result)}else{setStatus('warning','TRY AGAIN');setBusy(false)}}}catch(error){if(pending){pending.remove();pending=null}append('error',t.system,t.temporary);setStatus('warning','TRY AGAIN');haptic('notificationOccurred')}finally{if(booted)setBusy(false);input.focus()}});
      input.addEventListener('input',autoSize);input.addEventListener('keydown',function(event){if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();form.requestSubmit()}});window.addEventListener('error',function(){if(!booted){append('error',t.system,t.temporary);setStatus('warning','RECONNECT');retryButton()}});boot();
    })();
  </script>
</body>
</html>`;
}
